### ISSUE TITLE
/usr/local/include/vexcl/backend/opencl.hpp:39:10: fatal error: CL/cl.hpp: 没有那个文件或目录

### ISSUE THREAD

**Issue by dfy888** [ddemidov/vexcl#286]
/usr/local/include/vexcl/backend/opencl.hpp:39:10: fatal error: CL/cl.hpp: 没有那个文件或目录

本机应该是：#include <CL/cl.h>

**Comment by ddemidov** [comment]
Google translate says this means "no such file". The CL/cl.hpp should come
from your opencl SDK, or you can download it from khronos website, or there
is a copy in vexcl source provided for convenience.

--
Cheers,
Denis

**Comment by blattms** [comment]
@ddemidov for newer Linux distributions (without packages downloaded from NVIDIA or AMD/Rocm) that is no longer the case. E.g. on the current Debian versions with cuda/opencl packages from Debian there will be no CL/cl.hpp available.

[Khronos](KhronosGroup/OpenCL-CLHPP) has removed the CL/cl.hpp header a long time ago and CL/cl2.hpp should be used. Well, in current version CL/cl2.hpp is deprecated and will emit lots of warning and opencl.hpp should be used. But that is not yet available on all current Linux platforms.

The problem is that both NVIDIA ships rather old opencl cpp headers with their software and cl2.hpp will be missing. But if users install the package opencl-header in addition everything works (see OPM/opm-simulators#3644, OPM/opm-simulators#3652)

Would be cool if vexcl/opencl would support the the newer opencl headers:
- Use opencl.hpp if available, fall-back to cl2.hpp
- Use KernelFunctor instead of make_kernel
- Use std::vector<std::string> for Sources

**Comment by ddemidov** [comment]
On my machine there is no `CL/cl.hpp` as well, that is why vexcl includes its own version (downloaded from Khronos):
https://github.com/ddemidov/vexcl/tree/master/CL. I'll see if it is easy enough to check for and use if available `cl2.hpp` or `opencl.hpp`.

**Comment by blattms** [comment]
Indeed there is, but that is not installed and probably should not be. Hence if you are using an installed vexcl, that error occurs.

**Comment by ddemidov** [comment]
I've pushed the version that is compatible with `CL/opencl.hpp` to the [opencl-hpp](https://github.com/ddemidov/vexcl/tree/opencl-hpp) branch. Would that work for you?

I am willing to make this a permanent switch, since Khronos does recommend it, and it is backward compatible with platform includes (C-only).

By the way, `opencl-headers` on my installation (Arch linux) does not include any of the hpp headers, so either `CL/cl2.hpp` or `CL/opencl.hpp` would need to come from elsewhere (installed manually?).

> Use KernelFunctor instead of make_kernel

I don't think I use `cl::make_kernel` anywhere in vexcl code.

**Comment by blattms** [comment]
Thanks a lot for the prompt effort. Highly appreciated.

On Debian bullseye the branch works like a charm (with installed vexcl and amgcl). My only fear is that it might break on Linux distributions with slightly older opencl-headers version see e.g. https://github.com/OPM/opm-simulators/issues/3643#issuecomment-954796110_

I guess users or cmake need to somehow be able to select between cl2.hpp and opencl.hpp. Or we need accept the loads of warnings about deprecated cl2.hpp and always use that one for now.

Seem like on ArchLinux the C++ headers are part of package opencl-clhpp.
