### ISSUE TITLE
Confusing test executable output

### ISSUE THREAD

**Issue by yurivict** [ddemidov/vexcl#292]
The printout say that there are no errors, but the test fails and the error in the end isn't stated after the column:

```
$ ./work/.build/tests/custom_kernel
unknown location(0): fatal error: in "Test setup": cl::Error: clGetPlatformIDs
Running 2 test cases...

*** No errors detected
Test setup error: 
```

**Comment by ddemidov** [comment]
`fatal error: in "Test setup"` is Boost.Test's way of telling that the test setup failed, and `cl::Error: clGetPlatformIDs` is the OpenCL exception that probably means you don't have any recognized OpenCL devices on the test system. `No errors detected` is again Boost.Test's message. I guess it was not able to detect any errors because it failed to setup the test suite.

8e80910f tries to provide a little more help. The output now looks like:
```
Failed to initialize compute context
Error: clGetPlatformIDs(-1001: Unknown error)
unknown location(0): fatal error: in "Test setup": cl::Error: clGetPlatformIDs
Running 2 test cases...

*** No errors detected
Test setup error: 
```

**Comment by yurivict** [comment]
Ok, thanks!
